
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CAST = 45;
  public static final int ESTRING = 49;
  public static final int MASMAS = 43;
  public static final int DOSPUNTOS = 19;
  public static final int INTERROGACION = 18;
  public static final int MENOSMENOS = 44;
  public static final int AC = 22;
  public static final int CHAR = 46;
  public static final int POR = 14;
  public static final int GE = 8;
  public static final int MASUNARIO = 36;
  public static final int INTEGER = 34;
  public static final int FOR = 41;
  public static final int CP = 21;
  public static final int NOT = 9;
  public static final int AND = 10;
  public static final int LT = 5;
  public static final int CARACTER = 48;
  public static final int OR = 11;
  public static final int DIV = 15;
  public static final int CC = 23;
  public static final int IF = 37;
  public static final int LE = 6;
  public static final int EOF = 0;
  public static final int ASIG = 2;
  public static final int error = 1;
  public static final int COMA = 26;
  public static final int CADENA = 50;
  public static final int NUMERO_REAL = 29;
  public static final int MENOS = 13;
  public static final int IDENT = 31;
  public static final int EQ = 3;
  public static final int MENOSUNARIO = 16;
  public static final int CLL = 25;
  public static final int NEG = 35;
  public static final int ELSE = 38;
  public static final int PORCENT = 17;
  public static final int PUNTO = 28;
  public static final int VARIABLE = 32;
  public static final int WHILE = 40;
  public static final int FLOAT = 33;
  public static final int NE = 4;
  public static final int ALL = 24;
  public static final int AP = 20;
  public static final int GT = 7;
  public static final int NUMERO_ENTERO = 30;
  public static final int LENGTH = 47;
  public static final int PRINT = 42;
  public static final int DO = 39;
  public static final int PYC = 27;
  public static final int MAS = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ASIG",
  "EQ",
  "NE",
  "LT",
  "LE",
  "GT",
  "GE",
  "NOT",
  "AND",
  "OR",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "MENOSUNARIO",
  "PORCENT",
  "INTERROGACION",
  "DOSPUNTOS",
  "AP",
  "CP",
  "AC",
  "CC",
  "ALL",
  "CLL",
  "COMA",
  "PYC",
  "PUNTO",
  "NUMERO_REAL",
  "NUMERO_ENTERO",
  "IDENT",
  "VARIABLE",
  "FLOAT",
  "INTEGER",
  "NEG",
  "MASUNARIO",
  "IF",
  "ELSE",
  "DO",
  "WHILE",
  "FOR",
  "PRINT",
  "MASMAS",
  "MENOSMENOS",
  "CAST",
  "CHAR",
  "LENGTH",
  "CARACTER",
  "ESTRING",
  "CADENA"
  };
}

