
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\055\000\002\004\003\000\002\002\004\000\002\002" +
    "\004\000\002\002\003\000\002\003\003\000\002\003\003" +
    "\000\002\003\003\000\002\003\003\000\002\003\005\000" +
    "\002\005\004\000\002\014\005\000\002\014\004\000\002" +
    "\017\003\000\002\017\005\000\002\006\003\000\002\006" +
    "\003\000\002\007\006\000\002\016\003\000\002\016\005" +
    "\000\002\015\005\000\002\015\005\000\002\015\005\000" +
    "\002\015\005\000\002\015\004\000\002\015\005\000\002" +
    "\015\003\000\002\015\003\000\002\015\003\000\002\010" +
    "\007\000\002\022\002\000\002\023\002\000\002\012\012" +
    "\000\002\021\003\000\002\013\004\000\002\013\002\000" +
    "\002\020\005\000\002\020\005\000\002\020\005\000\002" +
    "\020\005\000\002\020\005\000\002\020\005\000\002\020" +
    "\004\000\002\020\005\000\002\020\005\000\002\020\005" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\127\000\016\007\012\010\022\011\004\020\006\023" +
    "\010\030\015\001\002\000\004\007\ufff3\001\002\000\020" +
    "\002\001\007\012\010\022\011\004\020\006\023\010\030" +
    "\015\001\002\000\016\007\012\010\022\011\004\020\006" +
    "\023\010\030\015\001\002\000\024\002\ufffd\007\ufffd\010" +
    "\ufffd\011\ufffd\020\ufffd\021\ufffd\023\ufffd\024\ufffd\030\ufffd" +
    "\001\002\000\004\043\uffe1\001\002\000\024\002\ufffa\007" +
    "\ufffa\010\ufffa\011\ufffa\020\ufffa\021\ufffa\023\ufffa\024\ufffa" +
    "\030\ufffa\001\002\000\004\017\120\001\002\000\004\002" +
    "\117\001\002\000\022\002\ufffe\007\ufffe\010\ufffe\011\ufffe" +
    "\020\ufffe\021\ufffe\023\ufffe\030\ufffe\001\002\000\004\043" +
    "\113\001\002\000\004\007\026\001\002\000\024\002\ufffb" +
    "\007\ufffb\010\ufffb\011\ufffb\020\ufffb\021\ufffb\023\ufffb\024" +
    "\ufffb\030\ufffb\001\002\000\024\002\ufffc\007\ufffc\010\ufffc" +
    "\011\ufffc\020\ufffc\021\ufffc\023\ufffc\024\ufffc\030\ufffc\001" +
    "\002\000\004\043\052\001\002\000\004\007\ufff2\001\002" +
    "\000\006\006\025\022\024\001\002\000\004\007\026\001" +
    "\002\000\024\002\ufff8\007\ufff8\010\ufff8\011\ufff8\020\ufff8" +
    "\021\ufff8\023\ufff8\024\ufff8\030\ufff8\001\002\000\010\006" +
    "\ufff5\017\030\022\ufff5\001\002\000\006\006\ufff7\022\ufff7" +
    "\001\002\000\014\004\033\005\034\007\031\013\032\043" +
    "\035\001\002\000\040\006\uffe8\012\uffe8\013\uffe8\014\uffe8" +
    "\015\uffe8\022\uffe8\031\uffe8\032\uffe8\033\uffe8\034\uffe8\035" +
    "\uffe8\036\uffe8\040\uffe8\041\uffe8\044\uffe8\001\002\000\014" +
    "\004\033\005\034\007\031\013\032\043\035\001\002\000" +
    "\040\006\uffe6\012\uffe6\013\uffe6\014\uffe6\015\uffe6\022\uffe6" +
    "\031\uffe6\032\uffe6\033\uffe6\034\uffe6\035\uffe6\036\uffe6\040" +
    "\uffe6\041\uffe6\044\uffe6\001\002\000\040\006\uffe7\012\uffe7" +
    "\013\uffe7\014\uffe7\015\uffe7\022\uffe7\031\uffe7\032\uffe7\033" +
    "\uffe7\034\uffe7\035\uffe7\036\uffe7\040\uffe7\041\uffe7\044\uffe7" +
    "\001\002\000\014\004\033\005\034\007\031\013\032\043" +
    "\035\001\002\000\016\006\ufff4\012\040\013\037\014\041" +
    "\015\042\022\ufff4\001\002\000\014\004\033\005\034\007" +
    "\031\013\032\043\035\001\002\000\014\004\033\005\034" +
    "\007\031\013\032\043\035\001\002\000\014\004\033\005" +
    "\034\007\031\013\032\043\035\001\002\000\014\004\033" +
    "\005\034\007\031\013\032\043\035\001\002\000\040\006" +
    "\uffeb\012\uffeb\013\uffeb\014\uffeb\015\uffeb\022\uffeb\031\uffeb" +
    "\032\uffeb\033\uffeb\034\uffeb\035\uffeb\036\uffeb\040\uffeb\041" +
    "\uffeb\044\uffeb\001\002\000\040\006\uffec\012\uffec\013\uffec" +
    "\014\uffec\015\uffec\022\uffec\031\uffec\032\uffec\033\uffec\034" +
    "\uffec\035\uffec\036\uffec\040\uffec\041\uffec\044\uffec\001\002" +
    "\000\040\006\uffee\012\uffee\013\uffee\014\041\015\042\022" +
    "\uffee\031\uffee\032\uffee\033\uffee\034\uffee\035\uffee\036\uffee" +
    "\040\uffee\041\uffee\044\uffee\001\002\000\040\006\uffed\012" +
    "\uffed\013\uffed\014\041\015\042\022\uffed\031\uffed\032\uffed" +
    "\033\uffed\034\uffed\035\uffed\036\uffed\040\uffed\041\uffed\044" +
    "\uffed\001\002\000\014\012\040\013\037\014\041\015\042" +
    "\044\050\001\002\000\040\006\uffe9\012\uffe9\013\uffe9\014" +
    "\uffe9\015\uffe9\022\uffe9\031\uffe9\032\uffe9\033\uffe9\034\uffe9" +
    "\035\uffe9\036\uffe9\040\uffe9\041\uffe9\044\uffe9\001\002\000" +
    "\040\006\uffea\012\uffea\013\uffea\014\uffea\015\uffea\022\uffea" +
    "\031\uffea\032\uffea\033\uffea\034\uffea\035\uffea\036\uffea\040" +
    "\uffea\041\uffea\044\uffea\001\002\000\016\004\033\005\034" +
    "\007\031\013\032\037\056\043\053\001\002\000\016\004" +
    "\033\005\034\007\031\013\032\037\056\043\053\001\002" +
    "\000\010\040\060\041\061\044\100\001\002\000\026\012" +
    "\040\013\037\014\041\015\042\031\065\032\070\033\071" +
    "\034\066\035\067\036\064\001\002\000\016\004\033\005" +
    "\034\007\031\013\032\037\056\043\053\001\002\000\010" +
    "\040\uffd8\041\uffd8\044\uffd8\001\002\000\016\004\033\005" +
    "\034\007\031\013\032\037\056\043\053\001\002\000\016" +
    "\004\033\005\034\007\031\013\032\037\056\043\053\001" +
    "\002\000\010\040\uffd6\041\uffd6\044\uffd6\001\002\000\010" +
    "\040\uffd7\041\uffd7\044\uffd7\001\002\000\014\004\033\005" +
    "\034\007\031\013\032\043\035\001\002\000\014\004\033" +
    "\005\034\007\031\013\032\043\035\001\002\000\014\004" +
    "\033\005\034\007\031\013\032\043\035\001\002\000\014" +
    "\004\033\005\034\007\031\013\032\043\035\001\002\000" +
    "\014\004\033\005\034\007\031\013\032\043\035\001\002" +
    "\000\014\004\033\005\034\007\031\013\032\043\035\001" +
    "\002\000\020\012\040\013\037\014\041\015\042\040\uffdd" +
    "\041\uffdd\044\uffdd\001\002\000\020\012\040\013\037\014" +
    "\041\015\042\040\uffdc\041\uffdc\044\uffdc\001\002\000\020" +
    "\012\040\013\037\014\041\015\042\040\uffdb\041\uffdb\044" +
    "\uffdb\001\002\000\020\012\040\013\037\014\041\015\042" +
    "\040\uffd9\041\uffd9\044\uffd9\001\002\000\020\012\040\013" +
    "\037\014\041\015\042\040\uffde\041\uffde\044\uffde\001\002" +
    "\000\020\012\040\013\037\014\041\015\042\040\uffda\041" +
    "\uffda\044\uffda\001\002\000\016\007\uffe4\010\uffe4\011\uffe4" +
    "\020\uffe4\023\uffe4\030\uffe4\001\002\000\016\007\012\010" +
    "\022\011\004\020\006\023\010\030\015\001\002\000\024" +
    "\002\uffe3\007\uffe3\010\uffe3\011\uffe3\020\uffe3\021\uffe3\023" +
    "\uffe3\024\uffe3\030\uffe3\001\002\000\024\002\uffdf\007\uffdf" +
    "\010\uffdf\011\uffdf\020\uffdf\021\uffdf\023\uffdf\024\105\030" +
    "\uffdf\001\002\000\024\002\uffe2\007\uffe2\010\uffe2\011\uffe2" +
    "\020\uffe2\021\uffe2\023\uffe2\024\uffe2\030\uffe2\001\002\000" +
    "\016\007\012\010\022\011\004\020\006\023\010\030\015" +
    "\001\002\000\024\002\uffe0\007\uffe0\010\uffe0\011\uffe0\020" +
    "\uffe0\021\uffe0\023\uffe0\024\uffe0\030\uffe0\001\002\000\010" +
    "\040\060\041\061\044\111\001\002\000\030\012\040\013" +
    "\037\014\041\015\042\031\065\032\070\033\071\034\066" +
    "\035\067\036\064\044\050\001\002\000\010\040\uffd5\041" +
    "\uffd5\044\uffd5\001\002\000\006\006\ufff6\022\ufff6\001\002" +
    "\000\014\004\033\005\034\007\031\013\032\043\035\001" +
    "\002\000\014\012\040\013\037\014\041\015\042\044\115" +
    "\001\002\000\004\006\116\001\002\000\024\002\uffe5\007" +
    "\uffe5\010\uffe5\011\uffe5\020\uffe5\021\uffe5\023\uffe5\024\uffe5" +
    "\030\uffe5\001\002\000\004\002\000\001\002\000\014\004" +
    "\033\005\034\007\122\013\032\043\035\001\002\000\004" +
    "\006\126\001\002\000\016\006\uffe8\012\uffe8\013\uffe8\014" +
    "\uffe8\015\uffe8\017\124\001\002\000\014\006\ufff0\012\040" +
    "\013\037\014\041\015\042\001\002\000\014\004\033\005" +
    "\034\007\031\013\032\043\035\001\002\000\014\006\uffef" +
    "\012\040\013\037\014\041\015\042\001\002\000\024\002" +
    "\ufff1\007\ufff1\010\ufff1\011\ufff1\020\ufff1\021\ufff1\023\ufff1" +
    "\024\ufff1\030\ufff1\001\002\000\020\007\012\010\022\011" +
    "\004\020\006\021\131\023\010\030\015\001\002\000\022" +
    "\002\uffff\007\uffff\010\uffff\011\uffff\020\uffff\021\uffff\023" +
    "\uffff\030\uffff\001\002\000\024\002\ufff9\007\ufff9\010\ufff9" +
    "\011\ufff9\020\ufff9\021\ufff9\023\ufff9\024\ufff9\030\ufff9\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\127\000\026\002\004\003\013\004\012\005\006\006" +
    "\015\007\017\010\016\012\010\014\022\021\020\001\001" +
    "\000\002\001\001\000\022\003\127\005\006\006\015\007" +
    "\017\010\016\012\010\014\022\021\020\001\001\000\024" +
    "\002\126\003\013\005\006\006\015\007\017\010\016\012" +
    "\010\014\022\021\020\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\017\111" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\017\026" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\015\035\001\001\000\002\001\001\000\004" +
    "\015\050\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\015\046\001\001\000\002\001\001\000\004\015\045" +
    "\001\001\000\004\015\044\001\001\000\004\015\043\001" +
    "\001\000\004\015\042\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\015\054" +
    "\020\053\001\001\000\006\015\107\020\106\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\015\054\020\056" +
    "\001\001\000\002\001\001\000\006\015\054\020\062\001" +
    "\001\000\006\015\054\020\061\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\015\076\001\001\000\004\015" +
    "\075\001\001\000\004\015\074\001\001\000\004\015\073" +
    "\001\001\000\004\015\072\001\001\000\004\015\071\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\022\100\001\001\000\022\003\101\005\006\006\015" +
    "\007\017\010\016\012\010\014\022\021\020\001\001\000" +
    "\004\023\102\001\001\000\004\013\103\001\001\000\002" +
    "\001\001\000\022\003\105\005\006\006\015\007\017\010" +
    "\016\012\010\014\022\021\020\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\015\113\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\015\122\016\120\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\015\124\001\001\000" +
    "\002\001\001\000\002\001\001\000\022\003\127\005\006" +
    "\006\015\007\017\010\016\012\010\014\022\021\020\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



TablaSimbolos ts=new TablaSimbolos();

Gc generador = new Gc();
private int var = 0;
private int etq = 0;
    
    // Generadores de referencias
    /**
     * Genera una variable con la estructura '$vX', siendo X un número.
     */
    private String nuevaTemp() {
        return "$t" + (var++);
    }
     /**
     * Genera una etiqueta con la estructura 'EX', siendo X un número.
     */
    private String crearEtiqueta() {
        return "Label " + (etq++);
    }
    public void error(String msg){
        System.err.println(msg);
        System.exit(1);
    }
 


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // lista ::= sents 
            {
              Object RESULT =null;
		generador.imprimirInstrucciones();
              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= lista EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // sents ::= sents sent 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sents",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // sents ::= sent 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sents",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // sent ::= sent_decl 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // sent ::= sentAsig 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // sent ::= sentPrint 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // sent ::= sentIF 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // sent ::= ALL sents CLL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // sent_decl ::= listaId PYC 
            {
              Tipo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_decl",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // listaId ::= listaId COMA aux2 
            {
              Tipo RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Tipo t = (Tipo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        if(ts.get(id)==null){
        ts.put(id,t); RESULT=t;
        }else{
            error("VARIABLE YA DECLARADA");
        }
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaId",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // listaId ::= tipo aux2 
            {
              Tipo RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Tipo t = (Tipo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        if(ts.get(id)==null){
        ts.put(id,t); RESULT=t;
        }else{
            error("VARIABLE YA DECLARADA");
        }
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaId",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // aux2 ::= ID 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT=id;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("aux2",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // aux2 ::= ID ASIG exp 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Tupla e = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        generador.generarAsignacion(id,e.codigo);
        RESULT=id;
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("aux2",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // tipo ::= INTEGER 
            {
              Tipo RESULT =null;
		RESULT=Tipo.I;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // tipo ::= FLOAT 
            {
              Tipo RESULT =null;
		RESULT=Tipo.F;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // sentAsig ::= ID ASIG aux PYC 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Tupla e = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
        Tipo t=ts.get(id);
        if(t!=null){
            if(t==e.tipo){   
                generador.generarAsignacion(id,e.codigo);
                RESULT=new Tupla(id,t);

            }else if(t==Tipo.F&&e.tipo==Tipo.I){
                String temp=nuevaTemp();
                generador.generarIntToFloat(temp,e.codigo);
                generador.generarAsignacion(id,temp);
                RESULT=new Tupla(id,Tipo.F);
            }else{
                error("TIPOS INCOMPATIBLES");
            }
        }
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentAsig",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // aux ::= exp 
            {
              Tupla RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Tupla e = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT=e;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("aux",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // aux ::= ID ASIG exp 
            {
              Tupla RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Tupla e = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    Tipo t=ts.get(id);
        if(t!=null){
            if(t==e.tipo){
                generador.generarAsignacion(id,e.codigo);
                RESULT=new Tupla(id,t);
            }else if(t==Tipo.F&&e.tipo==Tipo.I){
                String temp=nuevaTemp();
                generador.generarIntToFloat(temp,e.codigo);
                generador.generarAsignacion(id,temp);
                RESULT=new Tupla(id,Tipo.F);
            }else{
                error("TIPOS INCOMPATIBLES");
            }}
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("aux",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // exp ::= exp SUM exp 
            {
              Tupla RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Tupla e1 = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Tupla e2 = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    Tipo t;
    String temp=nuevaTemp();
    if(e1.tipo==Tipo.I&&e2.tipo==Tipo.I){
        t=Tipo.I;
        generador.generarOperacion(temp,e1.codigo,e2.codigo,"+"); 
        RESULT=new Tupla(temp,Tipo.I);
    }else if(e1.tipo==Tipo.I&&e2.tipo==Tipo.F){
        generador.generarIntToFloat(temp,e1.codigo);
        temp=nuevaTemp();
        generador.generarOperacion(temp,e1.codigo,e2.codigo,"+");
        RESULT=new Tupla(temp,Tipo.F);
    }else if(e1.tipo==Tipo.F&&e2.tipo==Tipo.I){
        generador.generarIntToFloat(temp,e2.codigo);
        temp=nuevaTemp();
        generador.generarOperacion(temp,e1.codigo,e2.codigo,"+");
        RESULT=new Tupla(temp,Tipo.F);
    }

    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // exp ::= exp RES exp 
            {
              Tupla RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Tupla e1 = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Tupla e2 = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    Tipo t;
    String temp=nuevaTemp();
    if(e1.tipo==Tipo.I&&e2.tipo==Tipo.I){
        t=Tipo.I;
        generador.generarOperacion(temp,e1.codigo,e2.codigo,"-"); 
        RESULT=new Tupla(temp,Tipo.I);
    }else if(e1.tipo==Tipo.I&&e2.tipo==Tipo.F){
        generador.generarIntToFloat(temp,e1.codigo);
        temp=nuevaTemp();
        generador.generarOperacion(temp,e1.codigo,e2.codigo,"-");
        RESULT=new Tupla(temp,Tipo.F);
    }else if(e1.tipo==Tipo.F&&e2.tipo==Tipo.I){
        generador.generarIntToFloat(temp,e2.codigo);
        temp=nuevaTemp();
        generador.generarOperacion(temp,e1.codigo,e2.codigo,"-");
        RESULT=new Tupla(temp,Tipo.F);
    }

    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // exp ::= exp MUL exp 
            {
              Tupla RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Tupla e1 = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Tupla e2 = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    Tipo t;
    String temp=nuevaTemp();
    if(e1.tipo==Tipo.I&&e2.tipo==Tipo.I){
        t=Tipo.I;
        generador.generarOperacion(temp,e1.codigo,e2.codigo,"*"); 
        RESULT=new Tupla(temp,Tipo.I);
    }else if(e1.tipo==Tipo.I&&e2.tipo==Tipo.F){
        generador.generarIntToFloat(temp,e1.codigo);
        temp=nuevaTemp();
        generador.generarOperacion(temp,e1.codigo,e2.codigo,"*");
        RESULT=new Tupla(temp,Tipo.F);
    }else if(e1.tipo==Tipo.F&&e2.tipo==Tipo.I){
        generador.generarIntToFloat(temp,e2.codigo);
        temp=nuevaTemp();
        generador.generarOperacion(temp,e1.codigo,e2.codigo,"*");
        RESULT=new Tupla(temp,Tipo.F);
    }

    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // exp ::= exp DIV exp 
            {
              Tupla RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Tupla e1 = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Tupla e2 = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    Tipo t;
    String temp=nuevaTemp();
    if(e1.tipo==Tipo.I&&e2.tipo==Tipo.I){
        t=Tipo.I;
        generador.generarOperacion(temp,e1.codigo,e2.codigo,"/"); 
        RESULT=new Tupla(temp,Tipo.I);
    }else if(e1.tipo==Tipo.I&&e2.tipo==Tipo.F){
        generador.generarIntToFloat(temp,e1.codigo);
        temp=nuevaTemp();
        generador.generarOperacion(temp,e1.codigo,e2.codigo,"/");
        RESULT=new Tupla(temp,Tipo.F);
    }else if(e1.tipo==Tipo.F&&e2.tipo==Tipo.I){
        generador.generarIntToFloat(temp,e2.codigo);
        temp=nuevaTemp();
        generador.generarOperacion(temp,e1.codigo,e2.codigo,"/");
        RESULT=new Tupla(temp,Tipo.F);
    }

    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // exp ::= RES exp 
            {
              Tupla RESULT =null;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Tupla e2 = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    
    String temp=nuevaTemp();
    
        
        generador.generarOperacion(temp,"",e2.codigo,"-"); 
        RESULT=new Tupla(temp,Tipo.I);
    

    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // exp ::= AP exp CP 
            {
              Tupla RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Tupla e1 = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
    
 
       
        RESULT=e1;
 
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // exp ::= ID 
            {
              Tupla RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        Tipo t=ts.get(i);
        
            RESULT=new Tupla(i,t);
        
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // exp ::= NUMF 
            {
              Tupla RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Float i = (Float)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT=new Tupla(i,Tipo.F);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // exp ::= NUMI 
            {
              Tupla RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT=new Tupla(i,Tipo.I);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // sentPrint ::= PRINT AP exp CP PYC 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Tupla e = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		  
            
            generador.generarPrint(e.codigo);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentPrint",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // NT$0 ::= 
            {
              Object RESULT =null;
		int templeft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int tempright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String temp = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		DosEtq c = (DosEtq)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

        generador.generarEtiqueta(c.si);
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // NT$1 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int templeft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int tempright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String temp = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		DosEtq c = (DosEtq)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
generador.generarSalto(temp);generador.generarEtiqueta(c.no);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$1",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // sentIF ::= iff AP cond CP NT$0 sent NT$1 parteELSE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int templeft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left;
		int tempright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).right;
		String temp = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		DosEtq c = (DosEtq)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		generador.generarEtiqueta(temp);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentIF",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // iff ::= IF 
            {
              String RESULT =null;
		RESULT=crearEtiqueta();
              CUP$parser$result = parser.getSymbolFactory().newSymbol("iff",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // parteELSE ::= ELSE sent 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parteELSE",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // parteELSE ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parteELSE",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // cond ::= exp EQ exp 
            {
              DosEtq RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Tupla e1 = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Tupla e2 = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        String si=crearEtiqueta();
        String no=crearEtiqueta();
        RESULT=new DosEtq(si,no);
        generador.generarSaltoCondicional(e1.codigo,"==",e2.codigo,RESULT.si);
        generador.generarSalto(RESULT.no);

        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // cond ::= exp LT exp 
            {
              DosEtq RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Tupla e1 = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Tupla e2 = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        String si=crearEtiqueta();
        String no=crearEtiqueta();
        RESULT=new DosEtq(si,no);

        generador.generarSaltoCondicional(e1.codigo,"<",e2.codigo,RESULT.si);
        generador.generarSalto(RESULT.no);

        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // cond ::= exp NE exp 
            {
              DosEtq RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Tupla e1 = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Tupla e2 = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        String si=crearEtiqueta();
        String no=crearEtiqueta();
        RESULT=new DosEtq(si,no);
        generador.generarSaltoCondicional(e1.codigo,"!=",e2.codigo,RESULT.si);
        generador.generarSalto(RESULT.no);

        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // cond ::= exp GT exp 
            {
              DosEtq RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Tupla e1 = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Tupla e2 = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        String si=crearEtiqueta();
        String no=crearEtiqueta();
        RESULT=new DosEtq(si,no);
        generador.generarSaltoCondicional(e1.codigo,">",e2.codigo,RESULT.si);
        generador.generarSalto(RESULT.no);

        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // cond ::= exp GE exp 
            {
              DosEtq RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Tupla e1 = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Tupla e2 = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        String si=crearEtiqueta();
        String no=crearEtiqueta();
        RESULT=new DosEtq(si,no);
        generador.generarSaltoCondicional(e1.codigo,">=",e2.codigo,RESULT.si);
        generador.generarSalto(RESULT.no);

        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // cond ::= exp LE exp 
            {
              DosEtq RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Tupla e1 = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Tupla e2 = (Tupla)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        String si=crearEtiqueta();
        String no=crearEtiqueta();
        RESULT=new DosEtq(si,no);
        generador.generarSaltoCondicional(e1.codigo,"<=",e2.codigo,RESULT.si);
        generador.generarSalto(RESULT.no);

        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // cond ::= NO cond 
            {
              DosEtq RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		DosEtq c = (DosEtq)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        
        RESULT=new DosEtq(c.no,c.si);
        

        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // cond ::= cond AND cond 
            {
              DosEtq RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		DosEtq e1 = (DosEtq)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		DosEtq e2 = (DosEtq)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
       
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // cond ::= cond OR cond 
            {
              DosEtq RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		DosEtq e1 = (DosEtq)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		DosEtq e2 = (DosEtq)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // cond ::= AP cond CP 
            {
              DosEtq RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		DosEtq c = (DosEtq)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT=c;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
