
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AC = 35;
  public static final int GE = 28;
  public static final int RES = 9;
  public static final int INTEGER = 7;
  public static final int FOR = 21;
  public static final int NUMI = 2;
  public static final int CP = 34;
  public static final int AND = 30;
  public static final int NUMF = 3;
  public static final int LT = 25;
  public static final int OR = 31;
  public static final int DIV = 11;
  public static final int CC = 36;
  public static final int IF = 17;
  public static final int ID = 5;
  public static final int LE = 26;
  public static final int EOF = 0;
  public static final int ASIG = 13;
  public static final int error = 1;
  public static final int MUL = 10;
  public static final int COMA = 16;
  public static final int EQ = 23;
  public static final int MENOSUNARIO = 12;
  public static final int CLL = 15;
  public static final int NEG = 32;
  public static final int NO = 29;
  public static final int ELSE = 18;
  public static final int WHILE = 20;
  public static final int FLOAT = 6;
  public static final int NE = 24;
  public static final int SUM = 8;
  public static final int ALL = 14;
  public static final int AP = 33;
  public static final int GT = 27;
  public static final int PRINT = 22;
  public static final int DO = 19;
  public static final int PYC = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMI",
  "NUMF",
  "PYC",
  "ID",
  "FLOAT",
  "INTEGER",
  "SUM",
  "RES",
  "MUL",
  "DIV",
  "MENOSUNARIO",
  "ASIG",
  "ALL",
  "CLL",
  "COMA",
  "IF",
  "ELSE",
  "DO",
  "WHILE",
  "FOR",
  "PRINT",
  "EQ",
  "NE",
  "LT",
  "LE",
  "GT",
  "GE",
  "NO",
  "AND",
  "OR",
  "NEG",
  "AP",
  "CP",
  "AC",
  "CC"
  };
}

