--EJERCICIO 1
SELECT NOMBRE, APELLIDO1, APELLIDO2
FROM PROFESORES
WHERE DEPARTAMENTO=1;

--EJERCICIO 2
SELECT NOMBRE, APELLIDO1, APELLIDO2
FROM PROFESORES
WHERE DEPARTAMENTO!=3;

SELECT * FROM SOL_1_2;


--EJERCICIO 3
SELECT NOMBRE, APELLIDO1, APELLIDO2--si pongo aqui , EMAIL pues puedo comprobar q me sale bn el email, pero esoquitalo para cd lo entregeus
FROM PROFESORES
WHERE LOWER (email) like '%@%lcc.uma.es';--pq es un email y tiene q tener @, EL @ ESTARA EN CUAQLUIER LADO POR ESO LOS %, PARA Q SEA CORREO PQ QUIERO Q SEA CORREO, POR ELLO QUIERO Q TNGA @ Y ME DA IGUAL DN ESTE Y ACABE EN UMA.LCC.ES
--ME DA IGUAL LO Q HAYA PERO Q TERMINE EN LCC.UMA.ES
--SI PONGO % AL PRINCIPIO SIGNIFICA Q ME DAIGUAL ... O SI ES % AL FINAL ES Q ... ME DA IGUAL LO Q HAYA
--PARA NO TENER PROBLEM CON juan y Juan paso los nombres a mayus
--UPPER (nombre) like '%JUAN%'
--lower (nombre) like '%juan%'
--%juan% juan antonio y anto juan
--juan% no entra anto juan pero si juan antonio


--PARA VER CUERPO DE LA TABLA
SELECT * 
FROM PROFESORES;

--EJERCICIO 4 y 8
SELECT 'El alumno' || NOMBRE ||' ' || APELLIDO1 || ' ' || APELLIDO2 || 'no dispone de correo'
FROM ALUMNOS 
WHERE EMAIL IS NULL;
SELECT * FROM SOL_1_4;
--para q salga la alumna gema en vez de el alumno gema usamos decode:
--decode es como un if
--hago slect* FROM alumno para ver como es tabla
SELECT * 
FROM ALUMNO;
--decode:si es masc escribe el alumno, en otro casoescribe la alumna
SELECT DECODE(GENERO , 'MASC', 'El alumno ','La alumna ') || NOMBRE ||' ' || APELLIDO1 || ' ' || APELLIDO2 || 'no dispone de correo'
FROM ALUMNOS 
WHERE EMAIL IS NULL;



--SIEMPRE LE PUEDO PONER UN ALIAS PARA Q EL TITULO DE TABLA NO SEA TAN LARGO
--las funciones las puedo usar tanto en el sele como en el where
--EJERCICIO 5

SELECT NOMBRE, (TEORICOS/CREDITOS)*100 "TEORICOS %", (PRACTICOS/CREDITOS)*100 "PRACTICOS %"
FROM ASIGNATURAS
WHERE CURSO=3;
--HAY Q SACAR PROPORCION EN PORENT
--LE HA PUESTO UN ALIAS (TEORICOS% Y PRACTICOS%) PARA Q NO APARAEZCA NOMBRE FEO
SELECT * FROM SOL_1_5;
--EN SELECT Y FROM PUEDO HACER CUALQUIER FUNCION Y CUALQUIER OPERACION MATEMATICA
--EJERCICIO 6
SELECT ALUMNO, CALIFICACION
FROM MATRICULAR
WHERE ASIGNATURA=112
ORDER BY ALUMNO;
SELECT * FROM SOL_1_6;
--EJERCICIO 7
SELECT NOMBRE, MUJERES+HOMBRES
FROM MUNICIPIO;
SELECT * FROM SOL_1_7;
--EJERCICIO 9
SELECT NOMBRE, APELLIDO1, APELLIDO2
FROM PROFESORES
WHERE ANTIGUEDAD < TO_DATE('01/01/1990', 'DD/MM/YYYY');--PASO 1/1/90 A FECHA
SELECT * FROM SOL_1_9;
--EJ 9 USANDO TOCHAR EN VEZ DE TODATE
SELECT NOMBRE, APELLIDO1,APELLIDO2
FROM PROFESORES
WHERE TO_NUMBER(TO_CHAR(ANTIGUEDAD, 'YYYY'))<1990; --CON TOCHAR ME QUEDO CON EL AÑO,LO PASA A NUM PARA PODER COMPARARLO
--EJEMPLO IMPORT SABERLO
SELECT ANTIGUEDAD, TO_CHAR(ANTIGUEDAD,'DAY')--DEVUELVE LA ANTIGUEDAD EN FORMATO DE SOLO DIA:LUNES P.EJ
FROM PROFESORES;
SELECT ANTIGUEDAD, TO_CHAR(ANTIGUEDAD,'DD')--LA ANTIGUEDAD EN FORMATO DIA PERO EN NUMERO:23
FROM PROFESORES;
--EJERCICIO 10
select nombre, apellido1, apellido2, trunc(MONTHS_BETWEEN(sysdate,
fecha_nacimiento)/12) "Edad"
from profesores
where (trunc(MONTHS_BETWEEN(sysdate, fecha_nacimiento)/12))<30;
SELECT * FROM SOL_1_10;
--EJERCICIO 11
SELECT NOMBRE,APELLIDO1,APELLIDO2,TRUNC(trunc(MONTHS_BETWEEN(sysdate,
ANTIGUEDAD)/12)/3) "TRIENIO"
FROM PROFESORES
WHERE TRUNC(trunc(MONTHS_BETWEEN(sysdate,
ANTIGUEDAD)/12)/3)>3;
SELECT * FROM SOL_1_11;
--EJERCICIO 12
select replace(upper(nombre), upper('Bases de datos'), upper('Almacenes de
Datos')) "Almacenes de Datos"
from asignaturas
where upper(nombre) like '%BASES DE DATOS%';
SELECT * FROM SOL_1_12;
--EJERCICIO 13
select nombre, nvl(TO_char(creditos), 'No asignado') "Creditos"
from asignaturas
where caracter like 'O_';
SELECT * FROM SOL_1_13;
--EJERCICIO 14
SELECT *
FROM ALUMNOS
WHERE trunc(MONTHS_BETWEEN(sysdate,
FECHA_PRIM_MATRICULA))<2;
SELECT * FROM SOL_1_14;
--EJERCICIO 15
SELECT *
FROM ALUMNOS
where MONTHS_BETWEEN(fecha_prim_matricula, fecha_nacimiento)<(18*12);
SELECT * FROM SOL_1_15;
--EJERCICIO 16
Select * from alumnos
where to_char(fecha_prim_matricula,'day') like 'lunes%';
SELECT * FROM SOL_1_16;